# Generated by Django 4.2.5 on 2023-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_colaborador',
            field=models.BooleanField(default=True),
        ),
    ]
