# Generated by Django 4.2.5 on 2023-10-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='marca',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='modelo',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='placa',
            new_name='plate',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='car',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='car',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
