# Generated by Django 4.2.5 on 2023-10-27 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='car', to='accounts.car'),
            preserve_default=False,
        ),
    ]
