# Generated by Django 4.2.5 on 2023-10-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ride_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(default='active', max_length=1),
        ),
    ]
