# Generated by Django 4.2.5 on 2023-10-27 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passageiros_aceitaram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
