# Generated by Django 4.2.5 on 2023-10-27 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_riderequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='passageiros_aceitaram',
        ),
        migrations.AddField(
            model_name='ride',
            name='accepted_by_passenger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='rides_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RideRequest',
        ),
    ]
