# Generated by Django 4.2.5 on 2023-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_ride_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ridein',
            field=models.IntegerField(default=0),
        ),
    ]
