# Generated by Django 4.2.5 on 2023-10-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_ridein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ridein',
            field=models.IntegerField(default=1),
        ),
    ]
