# Generated by Django 4.2.5 on 2023-10-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ridein',
        ),
    ]
