# Generated by Django 4.2.5 on 2023-10-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_customuser_ridein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='car_model',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
