# Generated by Django 4.2.5 on 2023-10-30 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_car_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='accepted_by_passenger',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='available_seats',
        ),
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(default='active', max_length=14),
        ),
    ]
