# Generated by Django 4.2.7 on 2023-11-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_requestparticipationinride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
